import {
  Autoformat,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  BlockQuote,
  Heading,
  Link,
  List,
  Table,
  TableToolbar,
  Image,
  ImageToolbar,
  ImageResize,
  ImageStyle,
  ImageUpload,
  ImageCaption,
  ImageTextAlternative,
  MediaEmbed,
  HorizontalLine,
  CodeBlock,
  Essentials,
  Paragraph,
  Undo,
  type EditorConfig,
} from "ckeditor5";

// Kept as one list so the allowed tags/attributes in
// services/sanitize.service.ts can be reasoned about against exactly this
// set of plugins — widen both together, never independently.
export const CKEDITOR_PLUGINS = [
  Essentials,
  Autoformat,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  BlockQuote,
  Link,
  List,
  Table,
  TableToolbar,
  Image,
  ImageToolbar,
  ImageResize,
  ImageStyle,
  ImageUpload,
  ImageCaption,
  ImageTextAlternative,
  MediaEmbed,
  HorizontalLine,
  CodeBlock,
  Undo,
];

export const CKEDITOR_TOOLBAR = [
  "undo",
  "redo",
  "|",
  "heading",
  "|",
  "bold",
  "italic",
  "underline",
  "strikethrough",
  "|",
  "link",
  "bulletedList",
  "numberedList",
  "|",
  "blockQuote",
  "insertTable",
  "mediaEmbed",
  "uploadImage",
  "horizontalLine",
  "codeBlock",
];

export const CKEDITOR_BASE_CONFIG: Partial<EditorConfig> = {
  licenseKey: "GPL",
  toolbar: CKEDITOR_TOOLBAR,
  image: {
    toolbar: [
      "imageStyle:inline",
      "imageStyle:block",
      "imageStyle:side",
      "|",
      "toggleImageCaption",
      "imageTextAlternative",
    ],
    resizeUnit: "%",
  },
  table: {
    contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"],
  },
};
